# Generated by Django 4.1.5 on 2023-04-19 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=14)),
                ("telefone", models.CharField(max_length=11)),
                ("data_nascimento", models.DateField()),
                ("profissao", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=30)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("nomeorc", models.CharField(max_length=200)),
                ("descr", models.CharField(max_length=400)),
                (
                    "proc1",
                    models.IntegerField(
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ]
                    ),
                ),
                ("val1", models.FloatField(blank=True, null=True)),
                (
                    "pag1",
                    models.IntegerField(
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ]
                    ),
                ),
                (
                    "proc2",
                    models.IntegerField(
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ]
                    ),
                ),
                ("val2", models.FloatField(blank=True, null=True)),
                (
                    "pag2",
                    models.IntegerField(
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ]
                    ),
                ),
                (
                    "proc3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ],
                        null=True,
                    ),
                ),
                ("val3", models.FloatField(blank=True, null=True)),
                (
                    "pag3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "proc4",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ],
                        null=True,
                    ),
                ),
                ("val4", models.FloatField(blank=True, null=True)),
                (
                    "pag4",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "proc5",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ],
                        null=True,
                    ),
                ),
                ("val5", models.FloatField(blank=True, null=True)),
                (
                    "pag5",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "proc6",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Abdominoplastia"),
                            (2, "Mini-abdominoplastia"),
                            (3, "Blefaroplastia Superior"),
                            (4, "Blefaroplastia Inferior"),
                            (5, "Blefaroplastia Superior e Inferior"),
                            (6, "Braquioplastia"),
                            (7, "Face"),
                            (8, "Lipoaspiração"),
                            (9, "Lipoaspiração de Dorso"),
                            (10, "Lipoaspiração de Submento"),
                            (11, "Mama Redutora"),
                            (12, "Mamoplastia de Aumento"),
                            (13, "Mastopexia"),
                            (14, "Mastopexia com Prótese"),
                            (15, "Ninfoplastia"),
                            (16, "Otoplastia"),
                            (17, "Retoque"),
                            (18, "Rinoplastia"),
                            (19, "Tumores cutâneos"),
                        ],
                        null=True,
                    ),
                ),
                ("val6", models.FloatField(blank=True, null=True)),
                (
                    "pag6",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1x Cartão de Débito"),
                            (2, "2x Cartão de Débito"),
                            (3, "3x Cartão de Débito"),
                            (4, "4x Cartão de Débito"),
                            (5, "5x Cartão de Débito"),
                            (6, "6x Cartão de Débito"),
                            (7, "1x Cartão de Crédito"),
                            (8, "2x Cartão de Crédito"),
                            (9, "3x Cartão de Crédito"),
                            (10, "4x Cartão de Crédito"),
                            (11, "5x Cartão de Crédito"),
                            (12, "6x Cartão de Crédito"),
                            (13, "Dinheiro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "pac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cliente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.enderecocliente"
            ),
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("nascimento", models.DateField()),
                (
                    "cargo",
                    models.IntegerField(
                        choices=[(1, "Médico"), (2, "Suporte"), (3, "Atendimento")]
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
