# Generated by Django 4.1.5 on 2023-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="pag2",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1x Cartão de Débito"),
                    (2, "2x Cartão de Débito"),
                    (3, "3x Cartão de Débito"),
                    (4, "4x Cartão de Débito"),
                    (5, "5x Cartão de Débito"),
                    (6, "6x Cartão de Débito"),
                    (7, "1x Cartão de Crédito"),
                    (8, "2x Cartão de Crédito"),
                    (9, "3x Cartão de Crédito"),
                    (10, "4x Cartão de Crédito"),
                    (11, "5x Cartão de Crédito"),
                    (12, "6x Cartão de Crédito"),
                    (13, "Dinheiro"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="proc2",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Abdominoplastia"),
                    (2, "Mini-abdominoplastia"),
                    (3, "Blefaroplastia Superior"),
                    (4, "Blefaroplastia Inferior"),
                    (5, "Blefaroplastia Superior e Inferior"),
                    (6, "Braquioplastia"),
                    (7, "Face"),
                    (8, "Lipoaspiração"),
                    (9, "Lipoaspiração de Dorso"),
                    (10, "Lipoaspiração de Submento"),
                    (11, "Mama Redutora"),
                    (12, "Mamoplastia de Aumento"),
                    (13, "Mastopexia"),
                    (14, "Mastopexia com Prótese"),
                    (15, "Ninfoplastia"),
                    (16, "Otoplastia"),
                    (17, "Retoque"),
                    (18, "Rinoplastia"),
                    (19, "Tumores cutâneos"),
                ],
                null=True,
            ),
        ),
    ]
