# Generated by Django 4.1.5 on 2023-04-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_orcamento_pag2_alter_orcamento_proc2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContagemOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contagem", models.IntegerField(default=0)),
            ],
        ),
    ]
